on:
  push:
    branches:
      - "main"
    paths:
      - "module.json"

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Update zip file
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r module.zip . module.json setup.mjs languages/ scripts/ sources/ styles/ templates/
