on:
  push:
    branches:
      - "main"
    paths:
      - "module.json"

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - name: Update zip file
        run: |
          git config --global user.name '${{github.actor}}'
          git config --global user.email '${{github.actor}}@users.noreply.github.com'
          git clean -f
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/krbz999/zhell-custom-stuff"
          git fetch origin "main"
          zip -r -q module.zip module.json setup.mjs languages/ scripts/ sources/ styles/ templates/
          git add module.zip
          git commit -m "zip-zap-a-rooni"
          git push -f
